/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.0-M17
 * Generated at: 2022-09-17 05:18:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class contactenos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<head>\n");
      out.write("        <link rel=\"icon\" href=\"assets/computer-investment.svg\">\n");
      out.write("        <title>CliniVet</title>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        \n");
      out.write("        <!--iconos fontawesome-->\n");
      out.write("        <script src=\"https://kit.fontawesome.com/3e9cb3f872.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("        \n");
      out.write("        <!--css bootstrap personalizado-->\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/bootstrap.css\">\n");
      out.write("        <!--My CSS-->\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/styles.css\">\n");
      out.write("        \n");
      out.write("        \n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("         <header>\n");
      out.write("            <nav class=\"navbar navbar-expand-lg navbar-dark bg-primary\">\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("                <div class=\"container-fluid\">\n");
      out.write("                    <a class=\"navbar-brand\" href=\"#\">CliniVet</span></a>\n");
      out.write("                    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("                        <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("                    </button>\n");
      out.write("                    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("                        <ul class=\"navbar-nav ml-auto\">\n");
      out.write("                            <li class=\"nav-item\">\n");
      out.write("                                <a class=\"nav-link\" href=\"index.html\">Inicio</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"nav-item\">\n");
      out.write("                                <a class=\"nav-link\" href=\"app.html\">App</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"nav-item\">\n");
      out.write("                                <a class=\"nav-link\" href=\"contactenos.jsp\">Registro</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"nav-item\">\n");
      out.write("                                <a class=\"nav-link\" href=\"comprar.html\">Comprar</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"nav-item\">\n");
      out.write("                                <a class=\"nav-link\" data-bs-toggle=\"modal\" data-bs-target=\"#modalTuto\">Instrucciones</a>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            </nav>\n");
      out.write("        </header>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        <div id=\"contenedor\">\n");
      out.write("            <center><h1>Registro </h1></center>\n");
      out.write("            <form action=\"procesar.jsp\" method=\"post\">\n");
      out.write("                <table border=\"0\" align=\"center\" class=\"tablaContactenos\">\n");
      out.write("                    <tr>\n");
      out.write("                        <th width=\"200px\">DNI</th>\n");
      out.write("                        <td width=\"300px\"><input type=\"text\" id=\"txtcod\" name=\"txtcod\" value=\"\" maxlength=\"5\" class=\"controles\"></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>Nombre</th>\n");
      out.write("                        <td><input type=\"text\" id=\"txtnom\" name=\"txtnom\" value=\"\" maxlength=\"50\" class=\"controles\"></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>Comentario</th>\n");
      out.write("                        <td><input type=\"text\" id=\"txtcom\" name=\"txtcom\" value=\"\" maxlength=\"50\" class=\"controles\"></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>MASCOTA</th>\n");
      out.write("                        <td>\n");
      out.write("                            <select name=\"cbolinea\" class=\"controles\">\n");
      out.write("                                <option value=\"mid\">gato</option>\n");
      out.write("                                <option value=\"top\">Perro</option>\n");
      out.write("                                <option value=\"jg\">Aves</option>\n");
      out.write("                                <option value=\"adc\">Roedores</option>\n");
      out.write("                                <option value=\"sup\">Reptiles</option>\n");
      out.write("                            </select>\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <td>SERVICIO</td>\n");
      out.write("                        <td>\n");
      out.write("                            <input type=\"radio\" id=\"optipo1\" name=\"optipo\" value=\"Mago\" checked>VACUNA\n");
      out.write("                            <input type=\"radio\" id=\"optipo2\" name=\"optipo\" value=\"Tanque\">OPERACION\n");
      out.write("                            <input type=\"radio\" id=\"optipo2\" name=\"optipo\" value=\"Tanque\">HIGIENE\n");
      out.write("                            <input type=\"radio\" id=\"optipo2\" name=\"optipo\" value=\"Tanque\">ADOPCION\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <td colspan=\"2\" align=\"center\">\n");
      out.write("                            <input type=\"submit\" id=\"btnenv\" name=\"btnenv\" value=\"Enviar\" class=\"botones\">\n");
      out.write("                            <input type=\"reset\" id=\"btnres\" name=\"btnres\" value=\"Restablecer\" class=\"botones\">\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                </table>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("         <footer class=\"footer pb-4 pt-4\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row text-center\">\n");
      out.write("                    <div class=\"col-12 col-lg\">\n");
      out.write("                        <a href=\"#\">Preguntas Frecuentes</a>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-12 col-lg\">\n");
      out.write("                        <a href=\"#\">Redes Sociales</a><br>\n");
      out.write("                        <a href=\"https://twitter.com/\" target=\"_blank\"><i class=\"fa-brands fa-twitter\">   </i></a>\n");
      out.write("                        <a href=\"https://www.instagram.com/\" target=\"_blank\"><i class=\"fa-brands fa-instagram\">   </i></a>\n");
      out.write("                        <a href=\"https://www.facebook.com/\" target=\"_blank\"><i class=\"fa-brands fa-facebook-f\">   </i></a>\n");
      out.write("                        <a href=\"https://www.linkedin.com/\" target=\"_blank\"><i class=\"fa-brands fa-linkedin-in\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-12 col-lg\">\n");
      out.write("                        <a href=\"#\">Contactanos</a>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-12 col-lg\">\n");
      out.write("                        <a href=\"#\">Equipo</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </footer>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
